services:
  mysql:
    image: mysql:8.0
    container_name: airline-mysql
    environment:
      MYSQL_ROOT_PASSWORD:  $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: airline_reservation_system
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: airline-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy